apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bhukkad-payment-pdb
  namespace: bhukkad
  labels:
    app: bhukkad
    component: payment
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bhukkad
      component: payment