apiVersion: v1
kind: Service
metadata:
  name: bhukkad-payment
  namespace: bhukkad
  labels:
    app: bhukkad
    component: payment
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8093
      protocol: TCP
      name: http
  selector:
    app: bhukkad
    component: payment