apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bhukkad-default-deny-ingress
  namespace: bhukkad
  labels:
    app: bhukkad
spec:
  podSelector: {}
  policyTypes:
    - Ingress
