-- ============================================================================
-- commerce service consolidated baseline (order + payment + delivery)
-- ============================================================================
-- GENERATED by merging the three pre-merge V1 baselines. Each source service
-- owned its own database and therefore its own copy of the platform tables
-- (outbox_events / idempotency_records / saga_* / dead_letter_events) and, in
-- some cases, the same business table with a DIFFERENT column set. Merging the
-- databases means each table must be emitted exactly once, so:
--
--   * platform tables are emitted once (payment is listed first and owns them);
--   * agent_cod_wallets / rider_earnings use PAYMENT's shape, because
--     V2__cod_wallet_rider_status is written as an additive repair that reads
--     total_cash_collected / total_cash_deposited and then adds delivery's
--     balance / status / updated_at on top;
--   * order_delivery_proofs uses ORDER's OTP shape; V25 adds delivery's
--     notes / signature columns.
--
-- All statements are IF NOT EXISTS / guarded so the file is re-runnable.
-- ============================================================================


-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.agent_cod_wallets (
    id bigint NOT NULL,
    agent_id bigint NOT NULL,
    total_cash_collected double precision DEFAULT 0.0 NOT NULL,
    total_cash_deposited double precision DEFAULT 0.0 NOT NULL,
    last_reconciled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.commission_tiers (
    id bigint NOT NULL,
    min_order_count integer NOT NULL,
    max_order_count integer,
    commission_pct numeric(5,2) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.commission_tiers ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.commission_tiers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.dead_letter_events (
    id bigint NOT NULL,
    event_type character varying(80) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    aggregate_id bigint NOT NULL,
    payload text NOT NULL,
    last_error character varying(1000),
    retry_count integer DEFAULT 0 NOT NULL,
    source character varying(20),
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    requeued_at timestamp(6) without time zone
);
ALTER TABLE public.dead_letter_events ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dead_letter_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.disputes (
    id bigint NOT NULL,
    payment_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    order_id bigint NOT NULL,
    reason character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    amount numeric(12,2) NOT NULL,
    resolution character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.disputes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.disputes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.dunning_runs (
    id bigint NOT NULL,
    payment_id bigint NOT NULL,
    attempt integer DEFAULT 1 NOT NULL,
    status character varying(20) NOT NULL,
    scheduled_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.dunning_runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dunning_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.idempotency_records (
    id bigint NOT NULL,
    idempotency_key character varying(128) NOT NULL,
    scope character varying(50) NOT NULL,
    owner_id bigint,
    status character varying(20) NOT NULL,
    response_payload text,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.idempotency_records ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.idempotency_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.outbox_events (
    id bigint NOT NULL,
    event_type character varying(80) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    aggregate_id bigint NOT NULL,
    payload text NOT NULL,
    status character varying(20) NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    last_error character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    published_at timestamp(6) without time zone,
    processing_started_at timestamp(6) without time zone
);
ALTER TABLE public.outbox_events ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.outbox_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.payments (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    currency character varying(3) DEFAULT 'INR'::character varying NOT NULL,
    status character varying(20) NOT NULL,
    provider character varying(50),
    provider_ref character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    purpose character varying(20) DEFAULT 'ORDER'::character varying,
    payment_method character varying(30) DEFAULT 'UPI'::character varying,
    wallet_amount numeric(12,2) DEFAULT 0,
    gateway_amount numeric(12,2) DEFAULT 0,
    transaction_id character varying(100),
    gateway_order_id character varying(100),
    gateway_payment_id character varying(100),
    idempotency_key character varying(100),
    payment_gateway_response text,
    completed_at timestamp(6) without time zone
);
ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.restaurant_settlements (
    id bigint NOT NULL,
    settlement_run_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    order_count integer NOT NULL,
    gross_amount numeric(12,2) NOT NULL,
    commission numeric(12,2) NOT NULL,
    net_amount numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.restaurant_settlements ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.restaurant_settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.rider_earnings (
    id bigint NOT NULL,
    agent_id bigint NOT NULL,
    order_id bigint NOT NULL,
    amount double precision NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    paid_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    bonus_amount double precision DEFAULT 0 NOT NULL,
    bonus_reason character varying(100)
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.saga_instances (
    id bigint NOT NULL,
    saga_type character varying(50) NOT NULL,
    saga_id character varying(100) NOT NULL,
    current_step character varying(50),
    status character varying(20) NOT NULL,
    payload text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.saga_instances ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.saga_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.saga_steps (
    id bigint NOT NULL,
    saga_instance_id bigint NOT NULL,
    step_order integer NOT NULL,
    step_name character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    payload text,
    compensation_payload text,
    error_message character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.saga_steps ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.saga_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.settlement_runs (
    id bigint NOT NULL,
    run_date date NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(14,2) DEFAULT 0 NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.settlement_runs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.settlement_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.wallet_balances (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    balance numeric(12,2) DEFAULT 0 NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.wallet_balances ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.wallet_balances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from payment ----
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    amount numeric(12,2) NOT NULL,
    balance_after numeric(12,2) NOT NULL,
    reference character varying(100),
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.wallet_transactions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.wallet_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.commission_tiers
    ADD CONSTRAINT commission_tiers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.dead_letter_events
    ADD CONSTRAINT dead_letter_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.dunning_runs
    ADD CONSTRAINT dunning_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT idempotency_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.restaurant_settlements
    ADD CONSTRAINT restaurant_settlements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.saga_instances
    ADD CONSTRAINT saga_instances_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.saga_steps
    ADD CONSTRAINT saga_steps_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.settlement_runs
    ADD CONSTRAINT settlement_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.dunning_runs
    ADD CONSTRAINT uk_dunning_payment_attempt UNIQUE (payment_id, attempt);
ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT uk_idempotency_scope_key UNIQUE (scope, idempotency_key);
ALTER TABLE ONLY public.wallet_balances
    ADD CONSTRAINT uk_wallet_customer UNIQUE (customer_id);
ALTER TABLE ONLY public.saga_steps
    ADD CONSTRAINT uq_saga_instance_step UNIQUE (saga_instance_id, step_order);
ALTER TABLE ONLY public.saga_instances
    ADD CONSTRAINT uq_saga_instances_saga_id UNIQUE (saga_id);
ALTER TABLE ONLY public.wallet_balances
    ADD CONSTRAINT wallet_balances_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.wallet_transactions
    ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id);
CREATE INDEX IF NOT EXISTS idx_disputes_customer ON public.disputes USING btree (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_disputes_payment ON public.disputes USING btree (payment_id);
CREATE INDEX IF NOT EXISTS idx_dlq_aggregate ON public.dead_letter_events USING btree (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_dlq_status_created ON public.dead_letter_events USING btree (status, created_at);
CREATE INDEX IF NOT EXISTS idx_idempotency_expires ON public.idempotency_records USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_outbox_aggregate ON public.outbox_events USING btree (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_outbox_status_created ON public.outbox_events USING btree (status, created_at);
CREATE INDEX IF NOT EXISTS idx_payment_purpose ON public.payments USING btree (purpose);
CREATE INDEX IF NOT EXISTS idx_payment_transaction ON public.payments USING btree (transaction_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer ON public.payments USING btree (customer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_payments_order ON public.payments USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments USING btree (status);
CREATE INDEX IF NOT EXISTS idx_saga_instance_status ON public.saga_steps USING btree (saga_instance_id, status);
CREATE INDEX IF NOT EXISTS idx_saga_steps_pending ON public.saga_steps USING btree (status, step_order);
CREATE INDEX IF NOT EXISTS idx_saga_type_status ON public.saga_instances USING btree (saga_type, status);
CREATE INDEX IF NOT EXISTS idx_settlement_restaurant ON public.restaurant_settlements USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_customer ON public.wallet_transactions USING btree (customer_id, created_at);
ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id);
ALTER TABLE ONLY public.dunning_runs
    ADD CONSTRAINT dunning_runs_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id);
ALTER TABLE ONLY public.saga_steps
    ADD CONSTRAINT fk_saga_steps_instance FOREIGN KEY (saga_instance_id) REFERENCES public.saga_instances(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.restaurant_settlements
    ADD CONSTRAINT restaurant_settlements_settlement_run_id_fkey FOREIGN KEY (settlement_run_id) REFERENCES public.settlement_runs(id);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.cart_item_customizations (
    id bigint NOT NULL,
    cart_item_id bigint NOT NULL,
    customization_choice_id bigint NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.cart_items (
    id bigint NOT NULL,
    cart_id bigint NOT NULL,
    menu_item_id bigint NOT NULL,
    item_name character varying(200) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    special_instructions text
);
ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.carts (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    restaurant_id bigint,
    coupon_code character varying(50)
);
ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.coupon_usages (
    id bigint NOT NULL,
    coupon_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    order_id bigint,
    used_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.coupon_usages ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.coupon_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.coupons (
    id bigint NOT NULL,
    code character varying(40) NOT NULL,
    description character varying(255) NOT NULL,
    discount_type character varying(20) NOT NULL,
    discount_value numeric(10,2) NOT NULL,
    minimum_order_amount numeric(10,2),
    maximum_discount_amount numeric(10,2),
    valid_from timestamp(6) without time zone NOT NULL,
    valid_until timestamp(6) without time zone NOT NULL,
    usage_limit integer,
    used_count integer DEFAULT 0 NOT NULL,
    per_user_limit integer,
    active boolean DEFAULT true NOT NULL,
    restaurant_id bigint
);
ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.customer_memberships (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    starts_at timestamp without time zone NOT NULL,
    ends_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.gift_cards (
    id bigint NOT NULL,
    code character varying(40) NOT NULL,
    balance numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    amount numeric(12,2) DEFAULT 0.0 NOT NULL,
    purchased_by bigint,
    recipient_email character varying(100),
    recipient_name character varying(100),
    message text,
    redeemed_by bigint,
    redeemed_at timestamp(6) without time zone
);
ALTER TABLE public.gift_cards ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.gift_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.gift_orders (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    sender_user_id bigint,
    recipient_name character varying(100),
    recipient_phone character varying(15),
    recipient_address_id bigint,
    message character varying(500),
    created_at timestamp(6) without time zone NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.group_order_members (
    id bigint NOT NULL,
    group_order_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    invite_phone character varying(15),
    amount_contribution numeric(12,2),
    paid boolean DEFAULT false,
    joined_at timestamp(6) without time zone
);
ALTER TABLE public.group_order_members ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.group_order_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.group_order_participants (
    group_order_id bigint NOT NULL,
    customer_id bigint NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.group_orders (
    id bigint NOT NULL,
    host_user_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    title character varying(100),
    placed_at timestamp(6) without time zone
);
ALTER TABLE public.group_orders ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.group_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.order_delivery_proofs (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    agent_id bigint,
    proof_type character varying(20) DEFAULT 'OTP'::character varying NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    otp_code_hash character varying(128),
    otp_issued_at timestamp without time zone,
    otp_expires_at timestamp without time zone,
    otp_attempts integer DEFAULT 0 NOT NULL,
    verified_at timestamp without time zone,
    photo_storage_key character varying(512),
    photo_uploaded_at timestamp without time zone,
    recipient_name character varying(120),
    capture_latitude double precision,
    capture_longitude double precision,
    notes text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.order_eta_snapshots (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    eta_minutes integer NOT NULL,
    actual_minutes integer,
    created_at timestamp(6) without time zone NOT NULL,
    eta_at timestamp(6) without time zone,
    confidence_low_minutes integer,
    confidence_high_minutes integer,
    traffic_factor double precision,
    surge_multiplier double precision,
    factors_summary character varying(500)
);
ALTER TABLE public.order_eta_snapshots ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_eta_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.order_invoices (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    invoice_number character varying(50) NOT NULL,
    gst_amount numeric(10,2) DEFAULT 0 NOT NULL,
    total numeric(12,2),
    created_at timestamp(6) without time zone NOT NULL,
    subtotal numeric(10,2) DEFAULT 0.0 NOT NULL,
    delivery_fee numeric(10,2) DEFAULT 0.0 NOT NULL,
    tax_amount numeric(10,2) DEFAULT 0.0 NOT NULL,
    cgst_amount numeric(10,2) DEFAULT 0.0 NOT NULL,
    sgst_amount numeric(10,2) DEFAULT 0.0 NOT NULL,
    discount_amount numeric(10,2) DEFAULT 0.0 NOT NULL,
    total_amount numeric(12,2) DEFAULT 0.0 NOT NULL,
    restaurant_gstin character varying(20),
    issued_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pdf_storage_key character varying(512),
    pdf_generated_at timestamp(6) without time zone,
    emailed_at timestamp(6) without time zone,
    email_recipient character varying(255),
    email_attempts integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.order_invoices ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.order_item_customizations (
    id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    customization_choice_id bigint NOT NULL,
    additional_price double precision
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    menu_item_id bigint NOT NULL,
    item_name character varying(200) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    special_instructions text
);
ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.order_timeline_events (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    event_type character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status character varying(30),
    message character varying(500),
    actor_id bigint,
    actor_role character varying(30)
);
ALTER TABLE public.order_timeline_events ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_timeline_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    currency character varying(3) DEFAULT 'INR'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    order_number character varying(30),
    delivered_at timestamp(6) without time zone,
    estimated_delivery_at timestamp(6) without time zone,
    subtotal numeric(12,2),
    delivery_fee numeric(12,2),
    tax_amount numeric(12,2),
    discount_amount numeric(12,2) DEFAULT 0.0,
    loyalty_points_redeemed integer DEFAULT 0,
    tip_amount numeric(12,2) DEFAULT 0.0,
    delivery_address_id bigint,
    special_instructions text,
    estimated_delivery_time integer,
    scheduled_at timestamp(6) without time zone,
    live_eta_minutes integer,
    live_eta_at timestamp(6) without time zone,
    wallet_amount_used numeric(12,2) DEFAULT 0.0,
    fulfillment_type character varying(20) DEFAULT 'DELIVERY'::character varying,
    device_id character varying(100),
    guest_phone character varying(20),
    gift_message character varying(500),
    recipient_name character varying(100),
    recipient_phone character varying(20),
    cancellation_reason character varying(500),
    cancelled_by character varying(20),
    coupon_id bigint,
    version bigint DEFAULT 0 NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.orders_archive (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    currency character varying(3) DEFAULT 'INR'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
)
PARTITION BY RANGE (created_at);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.orders_archive_default (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    currency character varying(3) DEFAULT 'INR'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.subscription_deliveries (
    id bigint NOT NULL,
    subscription_plan_id bigint NOT NULL,
    order_id bigint,
    scheduled_date date NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.subscription_plans (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    title character varying(100),
    items_json text,
    weekday character varying(10) NOT NULL,
    delivery_time time without time zone NOT NULL,
    delivery_address_id bigint NOT NULL,
    payment_method character varying(30) NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    start_date date NOT NULL,
    next_delivery_date date,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL
);

-- ---- from order ----
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    plan character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.orders_archive ATTACH PARTITION public.orders_archive_default DEFAULT;
ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT coupon_usages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_order_id_key UNIQUE (order_id);
ALTER TABLE ONLY public.gift_cards
    ADD CONSTRAINT gift_cards_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.group_order_members
    ADD CONSTRAINT group_order_members_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.group_orders
    ADD CONSTRAINT group_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.order_eta_snapshots
    ADD CONSTRAINT order_eta_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.order_invoices
    ADD CONSTRAINT order_invoices_order_id_key UNIQUE (order_id);
ALTER TABLE ONLY public.order_invoices
    ADD CONSTRAINT order_invoices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.order_timeline_events
    ADD CONSTRAINT order_timeline_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.orders_archive
    ADD CONSTRAINT orders_archive_pkey PRIMARY KEY (id, created_at);
ALTER TABLE ONLY public.orders_archive_default
    ADD CONSTRAINT orders_archive_default_pkey PRIMARY KEY (id, created_at);
ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT uk_coupon_code UNIQUE (code);
ALTER TABLE ONLY public.gift_cards
    ADD CONSTRAINT uk_gift_card_code UNIQUE (code);
ALTER TABLE ONLY public.group_order_members
    ADD CONSTRAINT uk_group_member UNIQUE (group_order_id, customer_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON public.cart_items USING btree (cart_id);
CREATE INDEX IF NOT EXISTS idx_carts_customer ON public.carts USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_coupon_active_valid ON public.coupons USING btree (active, valid_from, valid_until);
CREATE INDEX IF NOT EXISTS idx_coupon_restaurant ON public.coupons USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_coupon_usage_coupon_customer ON public.coupon_usages USING btree (coupon_id, customer_id);
CREATE INDEX IF NOT EXISTS idx_delivery_proof_agent ON public.order_delivery_proofs USING btree (agent_id, status);
CREATE INDEX IF NOT EXISTS idx_delivery_proof_status ON public.order_delivery_proofs USING btree (status, created_at);
CREATE INDEX IF NOT EXISTS idx_dispute_created ON public.disputes USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_dispute_status ON public.disputes USING btree (status);
CREATE INDEX IF NOT EXISTS idx_eta_order ON public.order_eta_snapshots USING btree (order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_gift_orders_sender ON public.gift_orders USING btree (sender_user_id);
CREATE INDEX IF NOT EXISTS idx_gop_customer ON public.group_order_participants USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_group_orders_host ON public.group_orders USING btree (host_user_id);
CREATE INDEX IF NOT EXISTS idx_membership_customer ON public.customer_memberships USING btree (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON public.orders USING btree (customer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant ON public.orders USING btree (restaurant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_scheduled_at ON public.orders USING btree (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_sub_del_plan ON public.subscription_deliveries USING btree (subscription_plan_id);
CREATE INDEX IF NOT EXISTS idx_sub_del_status ON public.subscription_deliveries USING btree (status);
CREATE INDEX IF NOT EXISTS idx_sub_status ON public.subscription_plans USING btree (status);
CREATE INDEX IF NOT EXISTS idx_sub_user ON public.subscription_plans USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_customer ON public.subscriptions USING btree (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_timeline_order ON public.order_timeline_events USING btree (order_id, created_at);
ALTER INDEX public.orders_archive_pkey ATTACH PARTITION public.orders_archive_default_pkey;
ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT coupon_usages_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.coupon_usages
    ADD CONSTRAINT coupon_usages_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.disputes
    ADD CONSTRAINT disputes_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.group_order_members
    ADD CONSTRAINT group_order_members_group_order_id_fkey FOREIGN KEY (group_order_id) REFERENCES public.group_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.order_eta_snapshots
    ADD CONSTRAINT order_eta_snapshots_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE ONLY public.order_invoices
    ADD CONSTRAINT order_invoices_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.order_timeline_events
    ADD CONSTRAINT order_timeline_events_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;
ALTER TABLE public.agent_cod_wallets ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.agent_cod_wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.agent_shifts (
    id bigint NOT NULL,
    agent_id bigint NOT NULL,
    start_time timestamp(6) without time zone NOT NULL,
    end_time timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.agent_shifts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.agent_shifts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.city_configs (
    id bigint NOT NULL,
    city_name character varying(100) NOT NULL,
    currency character varying(3) DEFAULT 'INR'::character varying NOT NULL,
    timezone character varying(50) DEFAULT 'Asia/Kolkata'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.city_configs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.city_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.delivery_agents (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.delivery_agents ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.delivery_agents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.delivery_assignments (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    agent_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    assigned_at timestamp(6) without time zone NOT NULL,
    picked_up_at timestamp(6) without time zone,
    delivered_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.delivery_assignments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.delivery_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.delivery_zones (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.delivery_zones ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.delivery_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE public.order_delivery_proofs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_delivery_proofs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.rider_delivery_batch_orders (
    id bigint NOT NULL,
    batch_id bigint NOT NULL,
    order_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.rider_delivery_batch_orders ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.rider_delivery_batch_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.rider_delivery_batches (
    id bigint NOT NULL,
    agent_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.rider_delivery_batches ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.rider_delivery_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE public.rider_earnings ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.rider_earnings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.rider_location_updates (
    id bigint NOT NULL,
    agent_id bigint NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.rider_location_updates ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.rider_location_updates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from delivery ----
CREATE TABLE IF NOT EXISTS public.zone_surge_rules (
    id bigint NOT NULL,
    zone_id bigint NOT NULL,
    day_of_week integer,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    multiplier numeric(5,2) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.zone_surge_rules ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.zone_surge_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.agent_cod_wallets
    ADD CONSTRAINT agent_cod_wallets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.agent_shifts
    ADD CONSTRAINT agent_shifts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.city_configs
    ADD CONSTRAINT city_configs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.delivery_agents
    ADD CONSTRAINT delivery_agents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.delivery_assignments
    ADD CONSTRAINT delivery_assignments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.delivery_zones
    ADD CONSTRAINT delivery_zones_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.order_delivery_proofs
    ADD CONSTRAINT order_delivery_proofs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rider_delivery_batch_orders
    ADD CONSTRAINT rider_delivery_batch_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rider_delivery_batches
    ADD CONSTRAINT rider_delivery_batches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rider_earnings
    ADD CONSTRAINT rider_earnings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rider_location_updates
    ADD CONSTRAINT rider_location_updates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.agent_cod_wallets
    ADD CONSTRAINT uk_agent_cod_wallet UNIQUE (agent_id);
ALTER TABLE ONLY public.rider_delivery_batch_orders
    ADD CONSTRAINT uk_batch_order UNIQUE (batch_id, order_id);
ALTER TABLE ONLY public.zone_surge_rules
    ADD CONSTRAINT zone_surge_rules_pkey PRIMARY KEY (id);
CREATE INDEX IF NOT EXISTS idx_assign_agent ON public.delivery_assignments USING btree (agent_id, status);
CREATE INDEX IF NOT EXISTS idx_assign_order ON public.delivery_assignments USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_delivery_proof_order ON public.order_delivery_proofs USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_rider_batch_agent ON public.rider_delivery_batches USING btree (agent_id, status);
CREATE INDEX IF NOT EXISTS idx_rider_earnings_agent ON public.rider_earnings USING btree (agent_id);
CREATE INDEX IF NOT EXISTS idx_rider_location_agent ON public.rider_location_updates USING btree (agent_id, recorded_at);
ALTER TABLE ONLY public.agent_cod_wallets
    ADD CONSTRAINT agent_cod_wallets_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.delivery_agents(id);
ALTER TABLE ONLY public.agent_shifts
    ADD CONSTRAINT agent_shifts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.delivery_agents(id);
ALTER TABLE ONLY public.delivery_assignments
    ADD CONSTRAINT delivery_assignments_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.delivery_agents(id);
ALTER TABLE ONLY public.rider_delivery_batch_orders
    ADD CONSTRAINT rider_delivery_batch_orders_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.rider_delivery_batches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rider_delivery_batches
    ADD CONSTRAINT rider_delivery_batches_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.delivery_agents(id);
ALTER TABLE ONLY public.rider_earnings
    ADD CONSTRAINT rider_earnings_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.delivery_agents(id);
ALTER TABLE ONLY public.rider_location_updates
    ADD CONSTRAINT rider_location_updates_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.delivery_agents(id);
ALTER TABLE ONLY public.zone_surge_rules
    ADD CONSTRAINT zone_surge_rules_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.delivery_zones(id);
