-- order_delivery_proofs.id must be DB-generated: the entity uses
-- GenerationType.IDENTITY. The V1 baseline table declared a bare
-- "id bigint NOT NULL" (no sequence default), so every OTP issuance failed
-- with "null value in column id violates not-null constraint" (409 on the
-- delivery-proof API). Fresh V3-shaped tables already carry identity — the
-- guard keeps this migration idempotent for both shapes.
DO $$
BEGIN
  IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'order_delivery_proofs'
        AND column_name = 'id'
        AND column_default IS NULL
        AND is_identity = 'NO'
  ) THEN
      ALTER TABLE public.order_delivery_proofs
          ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;
