apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bhukkad-redis-pdb
  namespace: bhukkad
  labels:
    app: bhukkad
    component: redis
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bhukkad
      component: redis
