apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bhukkad-admin-analytics-pdb
  namespace: bhukkad
  labels:
    app: bhukkad
    component: admin-analytics
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bhukkad
      component: admin-analytics