apiVersion: v1
kind: Service
metadata:
  name: bhukkad-admin-analytics
  namespace: bhukkad
  labels:
    app: bhukkad
    component: admin-analytics
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8087
      protocol: TCP
      name: http
  selector:
    app: bhukkad
    component: admin-analytics