apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: bhukkad
  labels:
    app: bhukkad
    component: redis-cluster
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    bind 0.0.0.0
    requirepass ${REDIS_PASSWORD}
    masterauth ${REDIS_PASSWORD}
    maxmemory 1.5gb
    maxmemory-policy allkeys-lru
