spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 64
          min-idle: 8
          max-idle: 32
          max-wait: 5s

  datasource:
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_POOL_SIZE:10}
      metrics-tracker-class: com.zaxxer.hikari.metrics.prometheus.PrometheusMetricsTracker

app:
  environment: production

  events:
    external:
      enabled: true
      type: kafka
      kafka:
        listener-concurrency: 3
  outbox:
    wake:
      enabled: true
management:
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://tempo:9411/api/v2/spans}