apiVersion: v1
kind: PersistentVolume
metadata:
  name: bhukkad-mysql-pv
  namespace: bhukkad
  labels:
    app: bhukkad
    component: mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/bhukkad/mysql