apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhukkad-mysql-pvc
  namespace: bhukkad
  labels:
    app: bhukkad
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard