apiVersion: v1
kind: Service
metadata:
  name: bhukkad-delivery
  namespace: bhukkad
  labels:
    app: bhukkad
    component: delivery
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: bhukkad
    component: delivery