apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bhukkad-backups
  namespace: bhukkad
  labels:
    app: bhukkad
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
