apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bhukkad-ingress
  namespace: bhukkad
  labels:
    app: bhukkad
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "64"
    nginx.ingress.kubernetes.io/limit-rps: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: api.bhukkad.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bhukkad-nginx
                port:
                  number: 80
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bhukkad-nginx
                port:
                  number: 80