apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bhukkad

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mysql/pv.yaml
  - mysql/pvc.yaml
  - mysql/configmap.yaml
  - mysql/deployment.yaml
  - mysql/mysql-replica.yaml
  - mysql/service.yaml
  - redis/configmap.yaml
  - redis/pvc.yaml
  - redis/deployment.yaml
  - redis/redis-sentinel.yaml
  - redis/service.yaml
  - rabbitmq/deployment.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/pdb.yaml
  - app/hpa.yaml
  - logging/fluent-bit-configmap.yaml
  - nginx/configmap.yaml
  - nginx/deployment.yaml
  - nginx/service.yaml
  - ingress.yaml

commonLabels:
  managed-by: kustomize
  project: bhukkad