apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: bhukkad-vault-store
  namespace: bhukkad
spec:
  provider:
    vault:
      server: "https://vault.bhukkad.internal:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "bhukkad-api"
          serviceAccountRef:
            name: "bhukkad-app"
