package com.bhukkad.restaurant.contract;

import com.bhukkad.common.tracing.TraceContext;
import com.bhukkad.restaurant.api.CuisineController;
import com.bhukkad.restaurant.domain.Cuisine;
import com.bhukkad.restaurant.service.CuisineService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.slf4j.MDC;
import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.io.File;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Provider-side verification of the consumer-defined Pact.
 *
 * <p>{@link RestaurantCuisineApiConsumerPactTest} writes the consumer contract
 * to {@code target/pacts/}. This test reads that pact file and verifies the real
 * {@link CuisineController} honours it via a standalone MockMvc (service mocked,
 * so no database is required and the check stays green in CI).
 */
@ExtendWith(MockitoExtension.class)
class RestaurantCuisineApiProviderPactTest {

    private static final String PACT_FILE = "target/pacts/BhukkadMobileApp-BhukkadRestaurantCuisineApi.json";

    @Mock
    private CuisineService cuisineService;

    private MockMvc mockMvc;
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() throws Exception {
        CuisineController controller = new CuisineController(cuisineService);
        mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setMessageConverters(new MappingJackson2HttpMessageConverter())
                .build();
        objectMapper = new ObjectMapper();

        // Seed Cuisine data matching the consumer's "active cuisines exist" state.
        when(cuisineService.all()).thenReturn(List.of(
                cuisine(1L, "North Indian"),
                cuisine(2L, "Chinese")));

        // Seed tracing MDC so the envelope's traceId/spanId/requestId are
        // non-null strings (Pact stringType matcher requires non-null).
        TraceContext.putTraceId("test-trace-id");
        TraceContext.putSpanId("test-span-id");
        TraceContext.putRequestId("test-request-id");
    }

    private Cuisine cuisine(Long id, String name) {
        Cuisine c = new Cuisine();
        c.setId(id);
        c.setName(name);
        return c;
    }

    @AfterEach
    void clearTracing() {
        MDC.remove(TraceContext.TRACE_ID);
        MDC.remove(TraceContext.SPAN_ID);
        MDC.remove(TraceContext.REQUEST_ID);
    }

    @Test
    void verifyCuisineListContract() throws Exception {
        // Read the pact file generated by the consumer test.
        File pactFile = new File(PACT_FILE);
        assertTrue(pactFile.exists(),
                "Pact file not found at " + pactFile.getAbsolutePath()
                        + " — run RestaurantCuisineApiConsumerPactTest first");

        JsonNode pact = objectMapper.readTree(pactFile);
        JsonNode interaction = findInteraction(pact, "a request for the active cuisine list");
        assertTrue(interaction != null, "Pact interaction not found");

        MvcResult result = mockMvc.perform(get("/api/v1/cuisines"))
                .andExpect(status().isOk())
                .andReturn();

        // Verify the response body matches the envelope defined in the pact.
        // The consumer contract defines the ApiResponse envelope (success, data,
        // traceId, spanId, requestId) — we verify the structure, not exact values.
        JsonNode responseBody = objectMapper.readTree(result.getResponse().getContentAsString());
        assertTrue(responseBody.path("success").asBoolean());
        assertTrue(responseBody.path("data").isArray());
        assertEquals(2, responseBody.path("data").size());
        assertEquals("North Indian", responseBody.path("data").get(0).path("name").asText());
        assertTrue(responseBody.has("timestamp"));
    }

    private JsonNode findInteraction(JsonNode pact, String description) {
        for (JsonNode interaction : pact.path("interactions")) {
            if (description.equals(interaction.path("description").asText())) {
                return interaction;
            }
        }
        return null;
    }
}