apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bhukkad-restaurant-pdb
  namespace: bhukkad
  labels:
    app: bhukkad
    component: restaurant
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bhukkad
      component: restaurant
