apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: bhukkad
  labels:
    app: bhukkad
    component: opensearch
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  selector:
    app: bhukkad
    component: opensearch
