CREATE TABLE users (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  -- Identity registry only (V62 semantics): credentials + PII live on the
  -- per-role tables (customers/restaurant_owners/delivery_agents/admins).
  role VARCHAR(20) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  phone_verified_at TIMESTAMP(6),
  profile_completed BOOLEAN NOT NULL DEFAULT FALSE,
  totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  totp_secret VARCHAR(64),
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6),
  profile_image_url VARCHAR(500),
  PRIMARY KEY (id)
);
-- Registry lookups by role/active; email/phone unique lookups live on the
-- per-role tables (idx_customer_email, idx_owner_email, idx_agent_email).
CREATE INDEX idx_user_role ON users (role);
CREATE INDEX idx_user_active ON users (active);
CREATE INDEX idx_user_role_active ON users (role, active);

CREATE TABLE customers (
  id BIGINT NOT NULL,
  loyalty_points INT NOT NULL DEFAULT 0,
  wallet_balance DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  PRIMARY KEY (id),
  CONSTRAINT fk_customer_user FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE restaurant_owners (
  id BIGINT NOT NULL,
  business_license VARCHAR(100),
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id),
  CONSTRAINT fk_owner_user FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE delivery_agents (
  id BIGINT NOT NULL,
  vehicle_type VARCHAR(50),
  vehicle_number VARCHAR(50),
  license_number VARCHAR(50),
  available BOOLEAN NOT NULL DEFAULT TRUE,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  current_latitude DOUBLE PRECISION,
  current_longitude DOUBLE PRECISION,
  average_rating DOUBLE PRECISION DEFAULT 0.0,
  total_deliveries INT DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT fk_agent_user FOREIGN KEY (id) REFERENCES users(id)
);
CREATE INDEX idx_agent_available ON delivery_agents (available);
CREATE INDEX idx_agent_verified ON delivery_agents (verified);
CREATE INDEX idx_agent_available_verified ON delivery_agents (available, verified);

CREATE TABLE admins (
  id BIGINT NOT NULL,
  email VARCHAR(100),
  password VARCHAR(255),
  full_name VARCHAR(100),
  phone_number VARCHAR(15),
  profile_image_url VARCHAR(500),
  totp_secret VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT uk_admins_email UNIQUE (email)
);
CREATE INDEX idx_admin_phone ON admins (phone_number);

CREATE TABLE addresses (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  pincode VARCHAR(10) NOT NULL,
  landmark VARCHAR(200),
  type VARCHAR(20),
  label VARCHAR(50),
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id),
  CONSTRAINT fk_address_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);
CREATE INDEX idx_address_customer ON addresses (customer_id);
CREATE INDEX idx_address_city ON addresses (city);
CREATE INDEX idx_address_pincode ON addresses (pincode);

CREATE TABLE cuisines (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  image_url VARCHAR(500),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT idx_cuisine_name UNIQUE (name)
);
CREATE INDEX idx_cuisine_active ON cuisines (active);

CREATE TABLE restaurants (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(2000),
  owner_id BIGINT NOT NULL,
  address_id BIGINT,
  image_url VARCHAR(500),
  opening_time TIME NOT NULL,
  closing_time TIME NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_open BOOLEAN NOT NULL DEFAULT TRUE,
  average_rating DOUBLE PRECISION DEFAULT 0.0,
  total_reviews INT DEFAULT 0,
  average_delivery_time INT,
  minimum_order_amount DOUBLE PRECISION,
  delivery_fee DOUBLE PRECISION,
  free_delivery_available BOOLEAN NOT NULL DEFAULT FALSE,
  free_delivery_above DOUBLE PRECISION,
  is_pure_veg BOOLEAN NOT NULL DEFAULT FALSE,
  license_number VARCHAR(50),
  fssai_number VARCHAR(50),
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6),
  PRIMARY KEY (id),
  CONSTRAINT fk_restaurant_owner FOREIGN KEY (owner_id) REFERENCES restaurant_owners(id),
  CONSTRAINT fk_restaurant_address FOREIGN KEY (address_id) REFERENCES addresses(id)
);
CREATE INDEX idx_restaurant_name ON restaurants (name);
CREATE INDEX idx_restaurant_owner ON restaurants (owner_id);
CREATE INDEX idx_restaurant_active ON restaurants (is_active);
CREATE INDEX idx_restaurant_open ON restaurants (is_open);
CREATE INDEX idx_restaurant_rating ON restaurants (average_rating);
CREATE INDEX idx_restaurant_active_open ON restaurants (is_active, is_open);

CREATE TABLE delivery_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  city VARCHAR(100) NOT NULL,
  center_latitude DOUBLE PRECISION NOT NULL,
  center_longitude DOUBLE PRECISION NOT NULL,
  radius_km DOUBLE PRECISION NOT NULL DEFAULT 5.0,
  base_delivery_fee DOUBLE PRECISION NOT NULL DEFAULT 40.0,
  per_km_fee DOUBLE PRECISION NOT NULL DEFAULT 5.0,
  surge_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_delivery_zones_city ON delivery_zones (city);
CREATE INDEX idx_delivery_zones_active ON delivery_zones (is_active);

CREATE TABLE menu_categories (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  restaurant_id BIGINT NOT NULL,
  display_order INT DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT fk_category_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);
CREATE INDEX idx_category_restaurant ON menu_categories (restaurant_id);
CREATE INDEX idx_category_active ON menu_categories (active);

CREATE TABLE customization_options (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  menu_item_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  multiple_selection BOOLEAN NOT NULL DEFAULT FALSE,
  min_selection INT DEFAULT 0,
  max_selection INT,
  PRIMARY KEY (id),
  CONSTRAINT fk_option_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id)
);
CREATE INDEX idx_option_item ON customization_options (menu_item_id);

CREATE TABLE customization_choices (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customization_option_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  additional_price DOUBLE PRECISION DEFAULT 0.0,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT fk_choice_option FOREIGN KEY (customization_option_id) REFERENCES customization_options(id)
);
CREATE INDEX idx_choice_option ON customization_choices (customization_option_id);

CREATE TABLE coupons (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(50) NOT NULL,
  description VARCHAR(500) NOT NULL,
  discount_type VARCHAR(20) NOT NULL,
  discount_value DOUBLE PRECISION NOT NULL,
  minimum_order_amount DOUBLE PRECISION,
  maximum_discount_amount DOUBLE PRECISION,
  valid_from TIMESTAMP(6) NOT NULL,
  valid_until TIMESTAMP(6) NOT NULL,
  usage_limit INT,
  used_count INT DEFAULT 0,
  per_user_limit INT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  restaurant_id BIGINT,
  PRIMARY KEY (id),
  CONSTRAINT idx_coupon_code UNIQUE (code),
  CONSTRAINT fk_coupon_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);
CREATE INDEX idx_coupon_active ON coupons (active);
CREATE INDEX idx_coupon_valid ON coupons (active, valid_from, valid_until);

CREATE TABLE promotion_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  campaign_type VARCHAR(30) NOT NULL,
  description TEXT,
  discount_percent DOUBLE PRECISION NULL,
  min_order_amount DOUBLE PRECISION NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gift_cards (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(20) NOT NULL UNIQUE,
  amount DOUBLE PRECISION NOT NULL,
  balance DOUBLE PRECISION NOT NULL,
  status VARCHAR(20) NOT NULL,
  purchased_by BIGINT NULL,
  recipient_email VARCHAR(100) NULL,
  recipient_name VARCHAR(100) NULL,
  message TEXT NULL,
  redeemed_by BIGINT NULL,
  redeemed_at TIMESTAMP(6) NULL,
  expires_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE group_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host_user_id BIGINT NULL,
  title VARCHAR(100) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP(6) NULL,
  placed_at TIMESTAMP(6) NULL
);

CREATE TABLE membership_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price_per_month DOUBLE PRECISION NOT NULL,
  free_delivery BOOLEAN NOT NULL DEFAULT FALSE,
  discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  restaurant_id BIGINT NOT NULL,
  title VARCHAR(100),
  items_json TEXT,
  weekday VARCHAR(10) NOT NULL ,
  delivery_time TIME NOT NULL,
  delivery_address_id BIGINT NOT NULL,
  payment_method VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' ,
  start_date DATE NOT NULL,
  next_delivery_date DATE,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
CREATE INDEX idx_sub_user ON subscription_plans (user_id);
CREATE INDEX idx_sub_status ON subscription_plans (status);

CREATE TABLE subscription_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_plan_id BIGINT NOT NULL,
  order_id BIGINT,
  scheduled_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' ,
  CONSTRAINT uq_sub_date UNIQUE (subscription_plan_id, scheduled_date),
  CONSTRAINT fk_sub_del_plan FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_sub_del_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
);
CREATE INDEX idx_sub_del_plan ON subscription_deliveries (subscription_plan_id);
CREATE INDEX idx_sub_del_status ON subscription_deliveries (status);

CREATE TABLE affiliate_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(120) NOT NULL,
  channel VARCHAR(40) NULL,
  reward_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_affiliate_code UNIQUE (code)
);

CREATE TABLE tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  domain VARCHAR(120) NOT NULL,
  brand_name VARCHAR(120) NULL,
  logo_url VARCHAR(500) NULL,
  theme_color VARCHAR(30) NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  CONSTRAINT uk_tenants_domain UNIQUE (domain)
);

CREATE TABLE city_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city VARCHAR(100) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Kolkata',
  supported_payment_methods VARCHAR(255),
  default_min_order_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  is_serviceable BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  CONSTRAINT uk_city_configs_city UNIQUE (city)
);

CREATE TABLE support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_number VARCHAR(30) NOT NULL UNIQUE,
  customer_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  category VARCHAR(50) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  resolution_notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_support_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_support_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE INDEX idx_support_customer ON support_tickets (customer_id);
CREATE INDEX idx_support_status ON support_tickets (status);

CREATE TABLE fraud_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NULL,
  event_type VARCHAR(50) NOT NULL,
  device_fingerprint VARCHAR(128),
  ip_address VARCHAR(45),
  details TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_fraud_customer ON fraud_events (customer_id);
CREATE INDEX idx_fraud_type ON fraud_events (event_type);

CREATE TABLE affiliate_referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_code_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  reward_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_affiliate_referral_code FOREIGN KEY (affiliate_code_id) REFERENCES affiliate_codes(id) ON DELETE CASCADE,
  CONSTRAINT fk_affiliate_referral_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);
CREATE INDEX idx_affiliate_referral_code ON affiliate_referrals (affiliate_code_id);
CREATE INDEX idx_affiliate_referral_status ON affiliate_referrals (status);

CREATE TABLE agent_cod_wallets (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  agent_id BIGINT NOT NULL,
  total_cash_collected DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  total_cash_deposited DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  last_reconciled_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_agent_cod_wallet_agent UNIQUE (agent_id),
  CONSTRAINT fk_agent_cod_wallet_agent FOREIGN KEY (agent_id) REFERENCES delivery_agents(id) ON DELETE CASCADE
);

CREATE TABLE agent_shifts (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  agent_id BIGINT NOT NULL,
  shift_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_shift_agent FOREIGN KEY (agent_id) REFERENCES delivery_agents(id) ON DELETE CASCADE
);
CREATE INDEX idx_shift_agent ON agent_shifts (agent_id);

CREATE TABLE campaign_usages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_usage_campaign FOREIGN KEY (campaign_id) REFERENCES promotion_campaigns(id),
  CONSTRAINT fk_usage_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_usage_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE INDEX idx_usage_campaign ON campaign_usages (campaign_id);
CREATE INDEX idx_usage_customer ON campaign_usages (campaign_id, customer_id);

CREATE TABLE coupon_usages (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  coupon_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  used_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_coupon_usage_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id),
  CONSTRAINT fk_coupon_usage_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_coupon_usage_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE INDEX idx_coupon_usage_coupon_customer ON coupon_usages (coupon_id, customer_id);

CREATE TABLE customer_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  starts_at TIMESTAMP NOT NULL,
  ends_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_membership_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_membership_plan FOREIGN KEY (plan_id) REFERENCES membership_plans(id)
);
CREATE INDEX idx_membership_customer ON customer_memberships (customer_id, status);

CREATE TABLE customer_notification_preferences (
  customer_id BIGINT NOT NULL,
  email_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sms_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  push_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  order_updates_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  promotions_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP(6) NULL,
  PRIMARY KEY (customer_id),
  CONSTRAINT fk_notif_pref_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE delivery_surveys (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  order_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  rating_delivery INT NULL,
  rating_food INT NULL,
  rating_speed INT NULL,
  comment VARCHAR(1000) NULL,
  submitted_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_survey_order UNIQUE (order_id),
  CONSTRAINT fk_survey_order FOREIGN KEY (order_id)    REFERENCES orders(id)    ON DELETE CASCADE,
  CONSTRAINT fk_survey_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);
CREATE INDEX idx_survey_customer ON delivery_surveys (customer_id);

CREATE TABLE device_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token VARCHAR(512) NOT NULL,
  platform VARCHAR(20) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  CONSTRAINT fk_device_token_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT uk_device_token UNIQUE (token)
);

CREATE TABLE disputes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  customer_evidence TEXT,
  rider_evidence TEXT,
  restaurant_evidence TEXT,
  resolution_notes TEXT,
  resolution VARCHAR(20) NULL,
  refund_amount DOUBLE PRECISION NULL,
  resolved_by BIGINT NULL,
  resolved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_dispute_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_dispute_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT uk_dispute_order UNIQUE (order_id)
);
CREATE INDEX idx_dispute_status ON disputes (status);
CREATE INDEX idx_dispute_created ON disputes (created_at);

CREATE TABLE dynamic_pricing_rules (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  restaurant_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(20) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  day_of_week INT NOT NULL,
  discount_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  surge_percent DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  min_order_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  max_discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  priority INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_dynamic_pricing_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

CREATE TABLE favorite_restaurants (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  restaurant_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_fav_customer_restaurant UNIQUE (customer_id, restaurant_id),
  CONSTRAINT fk_fav_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_fav_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);
CREATE INDEX idx_fav_customer ON favorite_restaurants (customer_id);

CREATE TABLE fraud_review_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fraud_event_id BIGINT NOT NULL,
  customer_id BIGINT NULL,
  action VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  notes VARCHAR(500) NULL,
  reviewed_by BIGINT NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fraud_review_event FOREIGN KEY (fraud_event_id) REFERENCES fraud_events(id) ON DELETE CASCADE,
  CONSTRAINT fk_fraud_review_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_fraud_review_user FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT uk_fraud_review_event UNIQUE (fraud_event_id)
);
CREATE INDEX idx_fraud_review_status ON fraud_review_queue (status);
CREATE INDEX idx_fraud_review_created ON fraud_review_queue (created_at);

CREATE TABLE gift_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE,
  sender_user_id BIGINT NULL,
  recipient_name VARCHAR(100) NULL,
  recipient_phone VARCHAR(15) NULL,
  recipient_address_id BIGINT NULL,
  message VARCHAR(500) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT fk_gift_orders_order FOREIGN KEY (order_id)        REFERENCES orders(id)  ON DELETE CASCADE,
  CONSTRAINT fk_gift_orders_sender FOREIGN KEY (sender_user_id)  REFERENCES users(id)   ON DELETE SET NULL
);
CREATE INDEX idx_gift_orders_sender ON gift_orders (sender_user_id);

CREATE TABLE group_order_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_order_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  invite_phone VARCHAR(15) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'INVITED',
  amount_contribution DOUBLE PRECISION NULL,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  joined_at TIMESTAMP(6) NULL,
  CONSTRAINT uq_group_member UNIQUE (group_order_id, user_id)
);
CREATE INDEX idx_group_member_user ON group_order_members (user_id);

CREATE TABLE inventory_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT NOT NULL,
  menu_item_id BIGINT NOT NULL,
  type VARCHAR(20) NOT NULL,
  current_stock INT NOT NULL,
  threshold INT NOT NULL,
  acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
  sent BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_inventory_alert_restaurant ON inventory_alerts (restaurant_id);
CREATE INDEX idx_inventory_alert_menu_item ON inventory_alerts (menu_item_id);
CREATE INDEX idx_inventory_alert_type ON inventory_alerts (type);
CREATE INDEX idx_inventory_alert_created_at ON inventory_alerts (created_at DESC);

CREATE TABLE menu_item_ratings (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  menu_item_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  rating INT NOT NULL,
  comment VARCHAR(500),
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_item_rating_order_item UNIQUE (order_id, menu_item_id),
  CONSTRAINT fk_mir_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_mir_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id),
  CONSTRAINT fk_mir_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE INDEX idx_mir_menu_item ON menu_item_ratings (menu_item_id);

CREATE TABLE menu_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT NOT NULL,
  version_number INT NOT NULL,
  label VARCHAR(100),
  snapshot_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP(6) NOT NULL,
  published_at TIMESTAMP(6) NULL,
  CONSTRAINT uq_menu_version UNIQUE (restaurant_id, version_number)
);
CREATE INDEX idx_menu_version_restaurant ON menu_versions (restaurant_id);

CREATE TABLE order_delivery_proofs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  agent_id BIGINT NULL,
  proof_type VARCHAR(20) NOT NULL DEFAULT 'OTP',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  otp_code_hash VARCHAR(128) NULL,
  otp_issued_at TIMESTAMP NULL,
  otp_expires_at TIMESTAMP NULL,
  otp_attempts INT NOT NULL DEFAULT 0,
  verified_at TIMESTAMP NULL,
  photo_storage_key VARCHAR(512) NULL,
  photo_uploaded_at TIMESTAMP NULL,
  recipient_name VARCHAR(120) NULL,
  capture_latitude DOUBLE PRECISION NULL,
  capture_longitude DOUBLE PRECISION NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_delivery_proof_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_delivery_proof_agent FOREIGN KEY (agent_id) REFERENCES delivery_agents(id),
  CONSTRAINT uk_delivery_proof_order UNIQUE (order_id)
);
CREATE INDEX idx_delivery_proof_agent ON order_delivery_proofs (agent_id, status);
CREATE INDEX idx_delivery_proof_status ON order_delivery_proofs (status, created_at);

CREATE TABLE promo_banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  subtitle VARCHAR(255),
  image_url VARCHAR(500),
  action_type VARCHAR(30) NOT NULL DEFAULT 'NONE',
  action_target VARCHAR(255),
  display_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_promo_active ON promo_banners (is_active, display_order);

CREATE TABLE restaurant_settlements (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  restaurant_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  order_amount DOUBLE PRECISION NOT NULL,
  commission_amount DOUBLE PRECISION NOT NULL,
  net_amount DOUBLE PRECISION NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  settled_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_settlement_order UNIQUE (order_id),
  CONSTRAINT fk_settlement_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id),
  CONSTRAINT fk_settlement_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE INDEX idx_settlement_restaurant_status ON restaurant_settlements (restaurant_id, status);



CREATE TABLE rider_delivery_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  CONSTRAINT fk_batch_agent FOREIGN KEY (agent_id) REFERENCES delivery_agents(id)
);
CREATE INDEX idx_batch_agent ON rider_delivery_batches (agent_id, status);

CREATE TABLE rider_delivery_batch_orders (
  batch_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  sequence_number INT NOT NULL,
  PRIMARY KEY (batch_id, order_id),
  CONSTRAINT fk_batch_order_batch FOREIGN KEY (batch_id) REFERENCES rider_delivery_batches(id),
  CONSTRAINT fk_batch_order_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT uk_batch_order UNIQUE (order_id)
);

CREATE TABLE rider_earnings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  paid_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rider_earning_agent FOREIGN KEY (agent_id) REFERENCES delivery_agents(id),
  CONSTRAINT fk_rider_earning_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT uk_rider_earning_order UNIQUE (order_id)
);

CREATE TABLE rider_location_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  agent_id BIGINT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rider_loc_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_rider_loc_agent FOREIGN KEY (agent_id) REFERENCES delivery_agents(id)
);
CREATE INDEX idx_rider_loc_order ON rider_location_updates (order_id, recorded_at DESC);

CREATE TABLE settlement_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_type VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
  restaurants_settled INT NOT NULL DEFAULT 0,
  agents_settled INT NOT NULL DEFAULT 0,
  total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  notes TEXT
);

CREATE TABLE trending_dishes (
  menu_item_id BIGINT NOT NULL,
  restaurant_id BIGINT NOT NULL,
  dish_name VARCHAR(255) NOT NULL,
  quantity_sold BIGINT NOT NULL DEFAULT 0,
  last_order_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (menu_item_id)
);

CREATE TABLE wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  payment_id BIGINT NULL,
  type VARCHAR(30) NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  balance_after DOUBLE PRECISION NOT NULL,
  description VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_wallet_tx_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_wallet_tx_payment FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE zone_surge_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id BIGINT NOT NULL,
  day_of_week INT NULL,
  start_hour INT NOT NULL,
  end_hour INT NOT NULL,
  surge_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_surge_zone FOREIGN KEY (zone_id) REFERENCES delivery_zones(id)
);
CREATE INDEX idx_surge_zone ON zone_surge_rules (zone_id, is_active);

-- Full-text search over restaurant names (replaces MySQL FULLTEXT on the
-- restaurants table, which is created in this migration).
CREATE INDEX ft_restaurant_name_gin ON restaurants USING GIN (to_tsvector('english', name));

-- Element-collection join tables (@ElementCollection on entities) — the
-- MySQL V1 created these with the parent table; they must exist for Hibernate.
CREATE TABLE restaurant_features (
    restaurant_id BIGINT NOT NULL,
    feature VARCHAR(100) NOT NULL,
    PRIMARY KEY (restaurant_id, feature),
    CONSTRAINT fk_restaurant_features FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE INDEX idx_restaurant_features_restaurant ON restaurant_features (restaurant_id);

CREATE TABLE restaurant_gallery (
    restaurant_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    PRIMARY KEY (restaurant_id, image_url),
    CONSTRAINT fk_restaurant_gallery FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE INDEX idx_restaurant_gallery_restaurant ON restaurant_gallery (restaurant_id);

CREATE TABLE restaurant_food_types (
    restaurant_id BIGINT NOT NULL,
    food_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (restaurant_id, food_type),
    CONSTRAINT fk_restaurant_food_types FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE INDEX idx_restaurant_food_types_restaurant ON restaurant_food_types (restaurant_id);

CREATE TABLE user_referral_codes (
    user_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, code),
    CONSTRAINT fk_user_referral_codes FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_referral_codes_user ON user_referral_codes (user_id);

-- Wallet domain owns its balance (V64 semantics); identity syncs via
-- CustomerWalletSyncPort, so no FK to users here.
CREATE TABLE wallet_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    balance NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_wallet_balance_customer UNIQUE (customer_id)
);

-- Many-to-many: restaurants ↔ cuisines.
CREATE TABLE restaurant_cuisines (
    restaurant_id BIGINT NOT NULL,
    cuisine_id BIGINT NOT NULL,
    PRIMARY KEY (restaurant_id, cuisine_id),
    CONSTRAINT fk_rc_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_rc_cuisine FOREIGN KEY (cuisine_id) REFERENCES cuisines(id) ON DELETE CASCADE
);
CREATE INDEX idx_rc_restaurant ON restaurant_cuisines (restaurant_id);
CREATE INDEX idx_rc_cuisine ON restaurant_cuisines (cuisine_id);
