-- V5: Missing tables from the MySQL baseline that were not carried over
-- into the PostgreSQL migration set.

-- orders_archive: retention/archival table for old orders.
-- PostgreSQL does not support MySQL-style RANGE COLUMNS partitioning,
-- so this is a plain table with a composite PK on (id, created_at).
CREATE TABLE IF NOT EXISTS orders_archive (
    id                    BIGINT       NOT NULL,
    order_number          VARCHAR(32)  NOT NULL,
    customer_id           BIGINT       NOT NULL,
    restaurant_id         BIGINT       NOT NULL,
    status                VARCHAR(32)  NULL,
    total_amount          NUMERIC(10,2) NULL,
    delivery_address_id   BIGINT       NULL,
    special_instructions  VARCHAR(500) NULL,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NULL,
    delivered_at          TIMESTAMP    NULL,
    estimated_delivery_at TIMESTAMP    NULL,
    archived_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, created_at)
);

CREATE INDEX IF NOT EXISTS idx_orders_archive_customer ON orders_archive (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_archive_status ON orders_archive (status);

-- data_export_requests: audit trail + payload store for "export my data" requests.
CREATE TABLE IF NOT EXISTS data_export_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    requested_at    TIMESTAMP(6) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    payload_json    TEXT NULL,
    completed_at    TIMESTAMP(6) NULL
);

CREATE INDEX IF NOT EXISTS idx_export_user_status ON data_export_requests (user_id, status, completed_at);
CREATE INDEX IF NOT EXISTS idx_export_requested_at ON data_export_requests (requested_at);
