apiVersion: v1
kind: Service
metadata:
  name: bhukkad-personalization
  namespace: bhukkad
  labels:
    app: bhukkad
    component: personalization
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: bhukkad
    component: personalization
