-- ============================================================================
-- engagement service consolidated baseline (social + growth + referral + survey + notification + realtime)
-- ============================================================================
-- GENERATED by merging the pre-merge V1 baselines. Each source service had its
-- own database and its own copy of the platform tables, and a few business
-- tables appear in more than one source. Each table is emitted exactly once
-- (first source listed wins); every statement is IF NOT EXISTS / guarded so the
-- file is re-runnable.
-- ============================================================================


-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.dead_letter_events (
    id bigint NOT NULL,
    event_type character varying(80) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    aggregate_id bigint NOT NULL,
    payload text NOT NULL,
    last_error character varying(1000),
    retry_count integer DEFAULT 0 NOT NULL,
    source character varying(20),
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    requeued_at timestamp(6) without time zone
);
ALTER TABLE public.dead_letter_events ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dead_letter_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.idempotency_records (
    id bigint NOT NULL,
    idempotency_key character varying(128) NOT NULL,
    scope character varying(50) NOT NULL,
    owner_id bigint,
    status character varying(20) NOT NULL,
    response_payload text,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.idempotency_records ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.idempotency_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.loyalty_points_ledger (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    points integer NOT NULL,
    transaction_type character varying(20) NOT NULL,
    reason character varying(100),
    reference_id character varying(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS public.loyalty_points_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.loyalty_points_ledger_id_seq OWNED BY public.loyalty_points_ledger.id;

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.outbox_events (
    id bigint NOT NULL,
    event_type character varying(80) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    aggregate_id bigint NOT NULL,
    payload text NOT NULL,
    status character varying(20) NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    last_error character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    published_at timestamp(6) without time zone,
    processing_started_at timestamp(6) without time zone
);
ALTER TABLE public.outbox_events ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.outbox_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.promotion_campaigns (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    campaign_type character varying(50),
    description text,
    discount_percent numeric(5,2),
    flat_discount_amount numeric(10,2),
    min_order_amount numeric(10,2),
    max_discount_amount numeric(10,2),
    free_delivery boolean DEFAULT false,
    priority integer DEFAULT 0,
    is_active boolean DEFAULT true,
    starts_at timestamp without time zone,
    ends_at timestamp without time zone,
    buy_quantity integer,
    get_quantity integer,
    get_discount_percent integer,
    target_segment character varying(50),
    applicable_menu_item_id bigint,
    restaurant_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS public.promotion_campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.promotion_campaigns_id_seq OWNED BY public.promotion_campaigns.id;

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.referral_records (
    id bigint NOT NULL,
    referrer_id bigint NOT NULL,
    referred_customer_id bigint,
    referral_code character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying,
    reward_credited boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone
);
CREATE SEQUENCE IF NOT EXISTS public.referral_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.referral_records_id_seq OWNED BY public.referral_records.id;

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.saga_instances (
    id bigint NOT NULL,
    saga_type character varying(50) NOT NULL,
    saga_id character varying(100) NOT NULL,
    current_step character varying(50),
    status character varying(20) NOT NULL,
    payload text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.saga_instances ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.saga_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ---- from growth ----
CREATE TABLE IF NOT EXISTS public.saga_steps (
    id bigint NOT NULL,
    saga_instance_id bigint NOT NULL,
    step_order integer NOT NULL,
    step_name character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    payload text,
    compensation_payload text,
    error_message character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.saga_steps ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.saga_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.loyalty_points_ledger ALTER COLUMN id SET DEFAULT nextval('public.loyalty_points_ledger_id_seq'::regclass);
ALTER TABLE ONLY public.promotion_campaigns ALTER COLUMN id SET DEFAULT nextval('public.promotion_campaigns_id_seq'::regclass);
ALTER TABLE ONLY public.referral_records ALTER COLUMN id SET DEFAULT nextval('public.referral_records_id_seq'::regclass);
ALTER TABLE ONLY public.dead_letter_events
    ADD CONSTRAINT dead_letter_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT idempotency_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.loyalty_points_ledger
    ADD CONSTRAINT loyalty_points_ledger_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.promotion_campaigns
    ADD CONSTRAINT promotion_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.referral_records
    ADD CONSTRAINT referral_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.saga_instances
    ADD CONSTRAINT saga_instances_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.saga_steps
    ADD CONSTRAINT saga_steps_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.idempotency_records
    ADD CONSTRAINT uk_idempotency_scope_key UNIQUE (scope, idempotency_key);
ALTER TABLE ONLY public.saga_steps
    ADD CONSTRAINT uq_saga_instance_step UNIQUE (saga_instance_id, step_order);
ALTER TABLE ONLY public.saga_instances
    ADD CONSTRAINT uq_saga_instances_saga_id UNIQUE (saga_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_active ON public.promotion_campaigns USING btree (is_active, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_dlq_aggregate ON public.dead_letter_events USING btree (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_dlq_status_created ON public.dead_letter_events USING btree (status, created_at);
CREATE INDEX IF NOT EXISTS idx_idempotency_expires ON public.idempotency_records USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_loyalty_ledger_created ON public.loyalty_points_ledger USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_loyalty_ledger_customer ON public.loyalty_points_ledger USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_outbox_aggregate ON public.outbox_events USING btree (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_outbox_status_created ON public.outbox_events USING btree (status, created_at);
CREATE INDEX IF NOT EXISTS idx_referral_code ON public.referral_records USING btree (referral_code);
CREATE INDEX IF NOT EXISTS idx_referral_referrer ON public.referral_records USING btree (referrer_id);
CREATE INDEX IF NOT EXISTS idx_saga_instance_status ON public.saga_steps USING btree (saga_instance_id, status);
CREATE INDEX IF NOT EXISTS idx_saga_steps_pending ON public.saga_steps USING btree (status, step_order);
CREATE INDEX IF NOT EXISTS idx_saga_type_status ON public.saga_instances USING btree (saga_type, status);
ALTER TABLE ONLY public.saga_steps
    ADD CONSTRAINT fk_saga_steps_instance FOREIGN KEY (saga_instance_id) REFERENCES public.saga_instances(id) ON DELETE CASCADE;

-- ---- from referral ----
CREATE TABLE IF NOT EXISTS public.affiliate_codes (
    id bigint NOT NULL,
    code character varying(40) NOT NULL,
    name character varying(120) NOT NULL,
    channel character varying(40),
    reward_amount double precision DEFAULT 0.0 NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS public.affiliate_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.affiliate_codes_id_seq OWNED BY public.affiliate_codes.id;

-- ---- from referral ----
CREATE TABLE IF NOT EXISTS public.affiliate_referrals (
    id bigint NOT NULL,
    affiliate_code_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    customer_email character varying(200),
    reward_amount double precision DEFAULT 0.0 NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS public.affiliate_referrals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.affiliate_referrals_id_seq OWNED BY public.affiliate_referrals.id;

-- ---- from referral ----
CREATE TABLE IF NOT EXISTS public.user_referral_codes (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    referral_code character varying(40) NOT NULL,
    referred_by bigint,
    referrals_count integer DEFAULT 0 NOT NULL,
    referral_bonus_earned double precision DEFAULT 0.0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
);
CREATE SEQUENCE IF NOT EXISTS public.user_referral_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.user_referral_codes_id_seq OWNED BY public.user_referral_codes.id;
ALTER TABLE ONLY public.affiliate_codes ALTER COLUMN id SET DEFAULT nextval('public.affiliate_codes_id_seq'::regclass);
ALTER TABLE ONLY public.affiliate_referrals ALTER COLUMN id SET DEFAULT nextval('public.affiliate_referrals_id_seq'::regclass);
ALTER TABLE ONLY public.user_referral_codes ALTER COLUMN id SET DEFAULT nextval('public.user_referral_codes_id_seq'::regclass);
ALTER TABLE ONLY public.affiliate_codes
    ADD CONSTRAINT affiliate_codes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.affiliate_referrals
    ADD CONSTRAINT affiliate_referrals_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.affiliate_codes
    ADD CONSTRAINT uk_affiliate_code UNIQUE (code);
ALTER TABLE ONLY public.user_referral_codes
    ADD CONSTRAINT uk_referral_code UNIQUE (referral_code);
ALTER TABLE ONLY public.user_referral_codes
    ADD CONSTRAINT user_referral_codes_pkey PRIMARY KEY (id);
CREATE INDEX IF NOT EXISTS idx_affiliate_codes_active ON public.affiliate_codes USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_affiliate_referral_code ON public.affiliate_referrals USING btree (affiliate_code_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_referral_customer ON public.affiliate_referrals USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_referral_status ON public.affiliate_referrals USING btree (status);
CREATE INDEX IF NOT EXISTS idx_referral_customer ON public.user_referral_codes USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_referral_referred_by ON public.user_referral_codes USING btree (referred_by);
ALTER TABLE ONLY public.affiliate_referrals
    ADD CONSTRAINT fk_affiliate_referral_code FOREIGN KEY (affiliate_code_id) REFERENCES public.affiliate_codes(id) ON DELETE CASCADE;

-- ---- from survey ----
CREATE TABLE IF NOT EXISTS public.delivery_surveys (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint,
    rating_delivery integer,
    rating_food integer,
    rating_speed integer,
    comment character varying(1000),
    submitted_at timestamp without time zone NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS public.delivery_surveys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.delivery_surveys_id_seq OWNED BY public.delivery_surveys.id;

-- ---- from survey ----
CREATE TABLE IF NOT EXISTS public.trending_dishes (
    menu_item_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    dish_name character varying(255) NOT NULL,
    quantity_sold bigint NOT NULL,
    last_order_at timestamp without time zone NOT NULL
);
ALTER TABLE ONLY public.delivery_surveys ALTER COLUMN id SET DEFAULT nextval('public.delivery_surveys_id_seq'::regclass);
ALTER TABLE ONLY public.delivery_surveys
    ADD CONSTRAINT delivery_surveys_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.trending_dishes
    ADD CONSTRAINT trending_dishes_pkey PRIMARY KEY (menu_item_id);
ALTER TABLE ONLY public.delivery_surveys
    ADD CONSTRAINT uk_survey_order UNIQUE (order_id);
CREATE INDEX IF NOT EXISTS idx_delivery_surveys_submitted_at ON public.delivery_surveys USING btree (submitted_at);
CREATE INDEX IF NOT EXISTS idx_survey_customer ON public.delivery_surveys USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_survey_restaurant ON public.delivery_surveys USING btree (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_trending_dishes_last_order_at ON public.trending_dishes USING btree (last_order_at);
CREATE INDEX IF NOT EXISTS idx_trending_dishes_quantity_sold ON public.trending_dishes USING btree (quantity_sold DESC);
CREATE INDEX IF NOT EXISTS idx_trending_dishes_restaurant ON public.trending_dishes USING btree (restaurant_id);

-- ---- from notification ----
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint NOT NULL,
    channel character varying(20) NOT NULL,
    recipient character varying(255) NOT NULL,
    template character varying(100),
    subject character varying(255),
    body text,
    status character varying(20) NOT NULL,
    provider_ref character varying(100),
    error character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
CREATE INDEX IF NOT EXISTS idx_notifications_channel_status ON public.notifications USING btree (channel, status);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications USING btree (recipient, created_at);
