-- Promotion tables predate the admin-ops insert surface and carry plain
-- NOT NULL ids; BY DEFAULT identity lets inserts mint ids while keeping
-- explicit-id seed rows legal.
ALTER TABLE public.promo_banners
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.promotion_campaigns
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
