apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bhukkad-postgresql-pdb
  namespace: bhukkad
  labels:
    app: bhukkad
    component: postgres
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bhukkad
      component: postgres
