"""
Bhukkad API catalog — descriptions and endpoint metadata for the integration test runner.
Paths use /api/v1 (canonical). Legacy /api/* is rewritten by LegacyApiPathRewriteFilter.
"""

API_CATALOG = [
    # ── Health & platform ──────────────────────────────────────────────────────
    {
        "group": "Health & Platform",
        "name": "Ping",
        "description": "Lightweight liveness probe. Returns pong, app name, instance id, and timestamp. Use for load-balancer health checks.",
        "method": "GET",
        "path": "/api/v1/health/ping",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "Health Summary",
        "description": "Basic application health: status, environment, active profiles, uptime, and instance metadata.",
        "method": "GET",
        "path": "/api/v1/health",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "Detailed Health",
        "description": "Extended health including MySQL primary/replica, Redis cache, JVM memory, and system info.",
        "method": "GET",
        "path": "/api/v1/health/detailed",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "Database Health",
        "description": "Checks primary MySQL connectivity, version, and response time.",
        "method": "GET",
        "path": "/api/v1/health/db",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "Read Replica Health",
        "description": "Probes read-replica datasource when configured; returns DISABLED if not set up.",
        "method": "GET",
        "path": "/api/v1/health/db/replica",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "Memory Health",
        "description": "Heap usage, non-heap usage, and memory status (HEALTHY / WARNING / CRITICAL).",
        "method": "GET",
        "path": "/api/v1/health/memory",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "Environment Info",
        "description": "Runtime environment details: profiles, Java version, OS, timezone, debug flag.",
        "method": "GET",
        "path": "/api/v1/health/env",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Health & Platform",
        "name": "OpenAPI Spec",
        "description": "Machine-readable OpenAPI 3 document for Swagger UI and client generation.",
        "method": "GET",
        "path": "/v3/api-docs",
        "auth": None,
        "expected": [200],
        "content_type": "json",
    },
    {
        "group": "Health & Platform",
        "name": "Swagger UI",
        "description": "Interactive API documentation UI.",
        "method": "GET",
        "path": "/swagger-ui/index.html",
        "auth": None,
        "expected": [200],
        "content_type": "html",
    },
    {
        "group": "Health & Platform",
        "name": "Actuator Health",
        "description": "Spring Boot Actuator health endpoint (if exposed).",
        "method": "GET",
        "path": "/actuator/health",
        "auth": None,
        "expected": [200, 404],
        "optional": True,
    },
    # ── Auth ───────────────────────────────────────────────────────────────────
    {
        "group": "Authentication",
        "name": "Register Customer",
        "description": "Creates a CUSTOMER account. Returns JWT access + refresh tokens on success.",
        "method": "POST",
        "path": "/api/v1/auth/register",
        "auth": None,
        "body_key": "register_customer",
        "expected": [200],
        "extract": {"customer_token": "data.token", "customer_id": "data.userId"},
        "phase": "setup",
    },
    {
        "group": "Authentication",
        "name": "Register Restaurant Owner",
        "description": "Creates a RESTAURANT_OWNER account for managing restaurants and menus.",
        "method": "POST",
        "path": "/api/v1/auth/register",
        "auth": None,
        "body_key": "register_owner",
        "expected": [200],
        "extract": {"owner_token": "data.token", "owner_id": "data.userId"},
        "phase": "setup",
    },
    {
        "group": "Authentication",
        "name": "Register Delivery Agent",
        "description": "Creates a DELIVERY_AGENT account for accepting and completing deliveries.",
        "method": "POST",
        "path": "/api/v1/auth/register",
        "auth": None,
        "body_key": "register_agent",
        "expected": [200],
        "extract": {"agent_token": "data.token", "agent_id": "data.userId"},
        "phase": "setup",
    },
    {
        "group": "Authentication",
        "name": "Login Customer",
        "description": "Authenticates a customer and returns JWT tokens.",
        "method": "POST",
        "path": "/api/v1/auth/login",
        "auth": None,
        "body_key": "login_customer",
        "expected": [200],
        "extract": {"customer_token": "data.token"},
        "phase": "setup",
    },
    {
        "group": "Authentication",
        "name": "Login Owner",
        "description": "Authenticates a restaurant owner.",
        "method": "POST",
        "path": "/api/v1/auth/login",
        "auth": None,
        "body_key": "login_owner",
        "expected": [200],
        "extract": {"owner_token": "data.token"},
        "phase": "setup",
    },
    {
        "group": "Authentication",
        "name": "Login Agent",
        "description": "Authenticates a delivery agent.",
        "method": "POST",
        "path": "/api/v1/auth/login",
        "auth": None,
        "body_key": "login_agent",
        "expected": [200],
        "extract": {"agent_token": "data.token"},
        "phase": "setup",
    },
    {
        "group": "Authentication",
        "name": "Login — Invalid Password",
        "description": "Negative test: wrong password should return 401 Unauthorized.",
        "method": "POST",
        "path": "/api/v1/auth/login",
        "auth": None,
        "body_key": "login_bad_password",
        "expected": [401],
    },
    {
        "group": "Authentication",
        "name": "Refresh Token",
        "description": "Issues a new access token using the refresh token (not the access token).",
        "method": "POST",
        "path": "/api/v1/auth/refresh-token",
        "auth": "customer_refresh",
        "expected": [200],
    },
    {
        "group": "Authentication",
        "name": "Verify Email",
        "description": "Marks the customer email as verified (dev/test flow).",
        "method": "POST",
        "path": "/api/v1/auth/verify-email?email={customer_email}",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Authentication",
        "name": "Forgot Password",
        "description": "Triggers password-reset email flow for the given address.",
        "method": "POST",
        "path": "/api/v1/auth/forgot-password?email={customer_email}",
        "auth": None,
        "expected": [200],
    },
    # ── Cuisines (public) ──────────────────────────────────────────────────────
    {
        "group": "Cuisines",
        "name": "List Active Cuisines",
        "description": "Returns all active cuisine types for restaurant filtering.",
        "method": "GET",
        "path": "/api/v1/cuisines",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Cuisines",
        "name": "Get Cuisine by ID",
        "description": "Fetches a single cuisine record. Uses cuisine id 1 if present in seed data.",
        "method": "GET",
        "path": "/api/v1/cuisines/1",
        "auth": None,
        "expected": [200, 404, 500],
        "optional": True,
    },
    # ── Customer profile ───────────────────────────────────────────────────────
    {
        "group": "Customer",
        "name": "Get Profile",
        "description": "Returns the logged-in customer's profile, addresses, wallet, and order count.",
        "method": "GET",
        "path": "/api/v1/customers/profile",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Update Profile",
        "description": "Updates customer name, phone, or profile image URL (partial update via query params).",
        "method": "PUT",
        "path": "/api/v1/customers/profile?fullName=API+Test+Customer",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Get Wallet Balance",
        "description": "Returns the customer's current wallet balance in INR.",
        "method": "GET",
        "path": "/api/v1/customers/wallet/balance",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Add Money to Wallet",
        "description": "Direct wallet credit (simulated top-up without payment gateway).",
        "method": "POST",
        "path": "/api/v1/customers/wallet/add-money?amount=500",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Get Loyalty Points",
        "description": "Returns accumulated loyalty points for the customer.",
        "method": "GET",
        "path": "/api/v1/customers/loyalty-points",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Register Device Token",
        "description": "Registers an FCM/APNs device token for push notifications.",
        "method": "POST",
        "path": "/api/v1/customers/device-tokens",
        "auth": "customer",
        "body_key": "device_token",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Add Delivery Address",
        "description": "Adds a new delivery address for the customer.",
        "method": "POST",
        "path": "/api/v1/customers/addresses",
        "auth": "customer",
        "body_key": "address",
        "expected": [200],
        "extract": {"address_id": "data.id"},
    },
    {
        "group": "Customer",
        "name": "List Addresses",
        "description": "Lists all saved delivery addresses.",
        "method": "GET",
        "path": "/api/v1/customers/addresses",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Customer",
        "name": "Set Default Address",
        "description": "Marks the given address as the default delivery location.",
        "method": "PUT",
        "path": "/api/v1/customers/addresses/{address_id}/set-default",
        "auth": "customer",
        "expected": [200],
        "requires": ["address_id"],
    },
    # ── Restaurant (owner + public) ────────────────────────────────────────────
    {
        "group": "Restaurant",
        "name": "Create Restaurant",
        "description": "Restaurant owner creates a new restaurant listing with address, hours, and delivery settings.",
        "method": "POST",
        "path": "/api/v1/restaurants/owner",
        "auth": "owner",
        "body_key": "restaurant",
        "expected": [200],
        "extract": {"restaurant_id": "data.id"},
    },
    {
        "group": "Restaurant",
        "name": "My Restaurants",
        "description": "Lists all restaurants owned by the authenticated owner.",
        "method": "GET",
        "path": "/api/v1/restaurants/owner/my-restaurants",
        "auth": "owner",
        "expected": [200],
    },
    {
        "group": "Restaurant",
        "name": "Toggle Restaurant Open",
        "description": "Opens or closes the restaurant for accepting orders.",
        "method": "PUT",
        "path": "/api/v1/restaurants/owner/{restaurant_id}/toggle-status?isOpen=true",
        "auth": "owner",
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Restaurant",
        "name": "Restaurant Analytics",
        "description": "Returns revenue, order volume, and rating analytics for the owner's restaurant.",
        "method": "GET",
        "path": "/api/v1/restaurants/owner/{restaurant_id}/analytics?days=30",
        "auth": "owner",
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Restaurant",
        "name": "List Public Restaurants",
        "description": "Browse all active restaurants (customer-facing discovery).",
        "method": "GET",
        "path": "/api/v1/restaurants/public",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Restaurant",
        "name": "Get Public Restaurant",
        "description": "Detailed public view of a single restaurant.",
        "method": "GET",
        "path": "/api/v1/restaurants/public/{restaurant_id}",
        "auth": None,
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Restaurant",
        "name": "Search Restaurants",
        "description": "Full-text search on restaurant name and description.",
        "method": "GET",
        "path": "/api/v1/restaurants/public/search?keyword=Bhukkad",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Restaurant",
        "name": "Nearby Restaurants",
        "description": "Geo search within radius (km) from latitude/longitude.",
        "method": "GET",
        "path": "/api/v1/restaurants/public/nearby?latitude=12.9716&longitude=77.5946&radiusKm=5",
        "auth": "customer",
        "expected": [200],
    },
    # ── Menu ───────────────────────────────────────────────────────────────────
    {
        "group": "Menu",
        "name": "Create Menu Category",
        "description": "Owner adds a menu category (e.g. Starters) to their restaurant.",
        "method": "POST",
        "path": "/api/v1/menu/categories?restaurantId={restaurant_id}",
        "auth": "owner",
        "body_key": "category",
        "expected": [200],
        "requires": ["restaurant_id"],
        "extract": {"category_id": "data.id"},
    },
    {
        "group": "Menu",
        "name": "List Categories",
        "description": "Lists menu categories for a restaurant.",
        "method": "GET",
        "path": "/api/v1/menu/categories/restaurant/{restaurant_id}",
        "auth": None,
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Menu",
        "name": "Create Menu Item",
        "description": "Owner adds a dish to a category with price, veg/non-veg, and metadata.",
        "method": "POST",
        "path": "/api/v1/menu/items",
        "auth": "owner",
        "body_key": "menu_item",
        "expected": [200],
        "requires": ["category_id"],
        "extract": {"menu_item_id": "data.id"},
    },
    {
        "group": "Menu",
        "name": "Get Menu Item",
        "description": "Public detail view of a menu item.",
        "method": "GET",
        "path": "/api/v1/menu/items/{menu_item_id}",
        "auth": None,
        "expected": [200],
        "requires": ["menu_item_id"],
    },
    {
        "group": "Menu",
        "name": "Items by Restaurant",
        "description": "All menu items for a restaurant.",
        "method": "GET",
        "path": "/api/v1/menu/items/restaurant/{restaurant_id}",
        "auth": None,
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Menu",
        "name": "Search Menu Items",
        "description": "Keyword search across menu item names.",
        "method": "GET",
        "path": "/api/v1/menu/items/search?keyword=Paneer",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Menu",
        "name": "Bestsellers",
        "description": "Top-selling items for a restaurant.",
        "method": "GET",
        "path": "/api/v1/menu/items/restaurant/{restaurant_id}/bestsellers",
        "auth": None,
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    # ── Cart ───────────────────────────────────────────────────────────────────
    {
        "group": "Cart",
        "name": "Add to Cart",
        "description": "Adds a menu item with quantity to the cart (same restaurant only).",
        "method": "POST",
        "path": "/api/v1/cart/add",
        "auth": "customer",
        "body_key": "cart_add",
        "expected": [200],
        "requires": ["menu_item_id"],
        "extract": {"cart_item_id": "data.items.0.id"},
    },
    {
        "group": "Cart",
        "name": "Get Cart",
        "description": "Returns the customer's cart, grouped by restaurant with subtotals.",
        "method": "GET",
        "path": "/api/v1/cart",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Cart",
        "name": "Update Cart Quantity",
        "description": "Changes quantity for a cart line item; quantity 0 removes the item.",
        "method": "PUT",
        "path": "/api/v1/cart/items/{cart_item_id}?quantity=2",
        "auth": "customer",
        "expected": [200],
        "requires": ["cart_item_id"],
    },
    # ── Orders ─────────────────────────────────────────────────────────────────
    {
        "group": "Orders",
        "name": "Place Order",
        "description": "Creates an order from the customer's cart for the given restaurant and delivery address. Supports Idempotency-Key header.",
        "method": "POST",
        "path": "/api/v1/orders/customer/create",
        "auth": "customer",
        "body_key": "order",
        "expected": [200],
        "requires": ["restaurant_id", "address_id"],
        "headers": {"Idempotency-Key": "{idempotency_key}"},
        "extract": {"order_id": "data.id", "order_number": "data.orderNumber"},
    },
    {
        "group": "Orders",
        "name": "My Orders (paged)",
        "description": "Paginated list of the customer's order history.",
        "method": "GET",
        "path": "/api/v1/orders/customer/my-orders?page=0&size=10",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Orders",
        "name": "My Orders (cursor)",
        "description": "Cursor-based pagination for order history (better for mobile infinite scroll).",
        "method": "GET",
        "path": "/api/v1/orders/customer/my-orders/cursor?size=10",
        "auth": "customer",
        "expected": [200],
    },
    {
        "group": "Orders",
        "name": "Get Order by ID",
        "description": "Full order detail for the owning customer.",
        "method": "GET",
        "path": "/api/v1/orders/customer/{order_id}",
        "auth": "customer",
        "expected": [200],
        "requires": ["order_id"],
    },
    {
        "group": "Orders",
        "name": "Track Order",
        "description": "Returns cached/live order status for customer tracking screen.",
        "method": "GET",
        "path": "/api/v1/orders/customer/track/{order_id}",
        "auth": "customer",
        "expected": [200],
        "requires": ["order_id"],
    },
    {
        "group": "Orders",
        "name": "Get Order by Number",
        "description": "Lookup order by human-readable order number (customer must own the order).",
        "method": "GET",
        "path": "/api/v1/orders/number/{order_number}",
        "auth": "customer",
        "expected": [200],
        "requires": ["order_number"],
    },
    {
        "group": "Orders",
        "name": "Restaurant Orders",
        "description": "Paginated orders for a restaurant (owner only).",
        "method": "GET",
        "path": "/api/v1/orders/restaurant/{restaurant_id}?page=0&size=10",
        "auth": "owner",
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Orders",
        "name": "Kitchen Queue",
        "description": "Active kitchen orders (placed → ready for pickup), cached in Redis.",
        "method": "GET",
        "path": "/api/v1/orders/restaurant/{restaurant_id}/kitchen-queue",
        "auth": "owner",
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Orders",
        "name": "Accept Order",
        "description": "Restaurant confirms a PLACED order.",
        "method": "PUT",
        "path": "/api/v1/orders/restaurant/{order_id}/accept",
        "auth": "owner",
        "expected": [200],
        "requires": ["order_id"],
    },
    {
        "group": "Orders",
        "name": "Mark Order Ready",
        "description": "Kitchen marks order READY_FOR_PICKUP for rider handoff.",
        "method": "PUT",
        "path": "/api/v1/orders/restaurant/{order_id}/ready",
        "auth": "owner",
        "expected": [200],
        "requires": ["order_id"],
    },
    {
        "group": "Orders",
        "name": "Assign Delivery Agent",
        "description": "Owner assigns a delivery agent to the order.",
        "method": "PUT",
        "path": "/api/v1/orders/restaurant/{order_id}/assign-delivery?agentId={agent_id}",
        "auth": "owner",
        "expected": [200],
        "requires": ["order_id", "agent_id"],
    },
    {
        "group": "Orders",
        "name": "Agent — My Deliveries",
        "description": "Paginated list of orders assigned to the delivery agent.",
        "method": "GET",
        "path": "/api/v1/orders/delivery/my-deliveries?page=0&size=10",
        "auth": "agent",
        "expected": [200],
    },
    {
        "group": "Orders",
        "name": "Agent — Mark Picked Up",
        "description": "Agent marks order OUT_FOR_DELIVERY.",
        "method": "PUT",
        "path": "/api/v1/orders/delivery/{order_id}/picked-up",
        "auth": "agent",
        "expected": [200],
        "requires": ["order_id"],
    },
    {
        "group": "Orders",
        "name": "Agent — Mark Delivered",
        "description": "Agent completes delivery; sets status DELIVERED.",
        "method": "PUT",
        "path": "/api/v1/orders/delivery/{order_id}/delivered",
        "auth": "agent",
        "expected": [200],
        "requires": ["order_id"],
    },
    {
        "group": "Orders",
        "name": "Cancel Order",
        "description": "Customer cancels order before it is out for delivery.",
        "method": "PUT",
        "path": "/api/v1/orders/customer/{cancel_order_id}/cancel?reason=Test+cancel",
        "auth": "customer",
        "expected": [200],
        "requires": ["cancel_order_id"],
        "optional": True,
    },
    # ── Delivery agent profile ───────────────────────────────────────────────────
    {
        "group": "Delivery",
        "name": "Agent Profile",
        "description": "Delivery agent profile and vehicle details.",
        "method": "GET",
        "path": "/api/v1/delivery/profile",
        "auth": "agent",
        "expected": [200],
    },
    {
        "group": "Delivery",
        "name": "Toggle Availability",
        "description": "Agent goes online/offline for new delivery offers.",
        "method": "PUT",
        "path": "/api/v1/delivery/toggle-availability?available=true",
        "auth": "agent",
        "expected": [200],
    },
    {
        "group": "Delivery",
        "name": "Update Location",
        "description": "Updates agent GPS coordinates for dispatch and tracking.",
        "method": "PUT",
        "path": "/api/v1/delivery/update-location?latitude=12.9716&longitude=77.5946",
        "auth": "agent",
        "expected": [200],
    },
    {
        "group": "Delivery",
        "name": "Earnings Summary",
        "description": "Total earnings, pending payout, and delivery stats for the agent.",
        "method": "GET",
        "path": "/api/v1/delivery/earnings/summary",
        "auth": "agent",
        "expected": [200],
    },
    {
        "group": "Delivery",
        "name": "Earnings History",
        "description": "Paginated payout/earning history.",
        "method": "GET",
        "path": "/api/v1/delivery/earnings?page=0&size=10",
        "auth": "agent",
        "expected": [200],
    },
    # ── Coupons ────────────────────────────────────────────────────────────────
    {
        "group": "Coupons",
        "name": "Active Coupons",
        "description": "Lists platform or restaurant-specific active coupons.",
        "method": "GET",
        "path": "/api/v1/coupons/active",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Coupons",
        "name": "Create Coupon",
        "description": "Owner or admin creates a discount coupon.",
        "method": "POST",
        "path": "/api/v1/coupons",
        "auth": "owner",
        "body_key": "coupon",
        "expected": [200],
        "requires": ["restaurant_id"],
        "extract": {"coupon_id": "data.id"},
    },
    # ── Reviews ────────────────────────────────────────────────────────────────
    {
        "group": "Reviews",
        "name": "Restaurant Reviews",
        "description": "Public list of reviews for a restaurant.",
        "method": "GET",
        "path": "/api/v1/reviews/restaurant/{restaurant_id}",
        "auth": None,
        "expected": [200],
        "requires": ["restaurant_id"],
    },
    {
        "group": "Reviews",
        "name": "Submit Review",
        "description": "Customer rates a delivered order (food + delivery ratings).",
        "method": "POST",
        "path": "/api/v1/reviews",
        "auth": "customer",
        "body_key": "review",
        "expected": [200],
        "requires": ["order_id"],
        "optional": True,
        "extract": {"review_id": "data.id"},
    },
    {
        "group": "Reviews",
        "name": "My Reviews",
        "description": "All reviews written by the logged-in customer.",
        "method": "GET",
        "path": "/api/v1/reviews/my-reviews",
        "auth": "customer",
        "expected": [200],
    },
    # ── Payments ───────────────────────────────────────────────────────────────
    {
        "group": "Payments",
        "name": "Payment for Order",
        "description": "Returns Razorpay/simulated payment details for checkout SDK.",
        "method": "GET",
        "path": "/api/v1/payments/orders/{order_id}",
        "auth": "customer",
        "expected": [200],
        "requires": ["order_id"],
        "optional": True,
    },
    # ── Admin ──────────────────────────────────────────────────────────────────
    {
        "group": "Admin",
        "name": "Dashboard",
        "description": "Platform KPIs: users, orders, revenue snapshot.",
        "method": "GET",
        "path": "/api/v1/admin/dashboard",
        "auth": "admin",
        "expected": [200],
        "requires": ["admin_token"],
        "optional": True,
    },
    {
        "group": "Admin",
        "name": "List Users",
        "description": "Paginated user directory with optional role/search filters.",
        "method": "GET",
        "path": "/api/v1/admin/users?page=0&size=10",
        "auth": "admin",
        "expected": [200],
        "requires": ["admin_token"],
        "optional": True,
    },
    {
        "group": "Admin",
        "name": "List Orders",
        "description": "Paginated all-platform orders with optional status filter.",
        "method": "GET",
        "path": "/api/v1/admin/orders?page=0&size=10",
        "auth": "admin",
        "expected": [200],
        "requires": ["admin_token"],
        "optional": True,
    },
    {
        "group": "Admin",
        "name": "Revenue Stats",
        "description": "Revenue breakdown for the last N days.",
        "method": "GET",
        "path": "/api/v1/admin/revenue?days=7",
        "auth": "admin",
        "expected": [200],
        "requires": ["admin_token"],
        "optional": True,
    },
    # ── Cache ──────────────────────────────────────────────────────────────────
    {
        "group": "Cache",
        "name": "Cache Health",
        "description": "Redis read/write probe and cache statistics.",
        "method": "GET",
        "path": "/api/v1/cache/health",
        "auth": None,
        "expected": [200],
    },
    {
        "group": "Cache",
        "name": "Cache Stats",
        "description": "Hit/miss and keyspace statistics from Redis.",
        "method": "GET",
        "path": "/api/v1/cache/stats",
        "auth": None,
        "expected": [200],
    },
    # ── Security negatives ─────────────────────────────────────────────────────
    {
        "group": "Security",
        "name": "No Token — Customer Route",
        "description": "Protected route without JWT should return 401/403.",
        "method": "GET",
        "path": "/api/v1/customers/profile",
        "auth": None,
        "expected": [401, 403],
    },
    {
        "group": "Security",
        "name": "Wrong Role — Owner Route as Customer",
        "description": "Customer token on owner-only route should be denied.",
        "method": "GET",
        "path": "/api/v1/restaurants/owner/my-restaurants",
        "auth": "customer",
        "expected": [401, 403],
    },
    # ── Logout ─────────────────────────────────────────────────────────────────
    {
        "group": "Authentication",
        "name": "Logout Customer",
        "description": "Invalidates the customer session/token.",
        "method": "POST",
        "path": "/api/v1/auth/logout",
        "auth": "customer",
        "expected": [200],
        "requires": ["customer_token"],
        "phase": "teardown",
    },
]

# Request body templates — {placeholders} resolved at runtime
BODY_TEMPLATES = {
    "register_customer": {
        "fullName": "API Test Customer",
        "email": "{customer_email}",
        "password": "{password}",
        "phoneNumber": "{customer_phone}",
        "role": "CUSTOMER",
    },
    "register_owner": {
        "fullName": "API Test Owner",
        "email": "{owner_email}",
        "password": "{password}",
        "phoneNumber": "{owner_phone}",
        "role": "RESTAURANT_OWNER",
    },
    "register_agent": {
        "fullName": "API Test Agent",
        "email": "{agent_email}",
        "password": "{password}",
        "phoneNumber": "{agent_phone}",
        "role": "DELIVERY_AGENT",
    },
    "register_admin": {
        "fullName": "API Test Admin",
        "email": "{admin_email}",
        "password": "{password}",
        "phoneNumber": "{admin_phone}",
        "role": "ADMIN",
    },
    "login_customer": {"email": "{customer_email}", "password": "{password}"},
    "login_owner": {"email": "{owner_email}", "password": "{password}"},
    "login_agent": {"email": "{agent_email}", "password": "{password}"},
    "login_admin": {"email": "{admin_email}", "password": "{password}"},
    "login_bootstrap_admin": {
        "email": "{bootstrap_admin_email}",
        "password": "{bootstrap_admin_password}",
    },
    "login_bad_password": {"email": "{customer_email}", "password": "wrong-password"},
    "device_token": {
        "token": "fcm-test-token-{run_id}",
        "platform": "ANDROID",
    },
    "address": {
        "addressLine1": "123 MG Road",
        "addressLine2": "Floor 2",
        "city": "Bangalore",
        "state": "Karnataka",
        "pincode": "560001",
        "landmark": "Near Metro",
        "type": "HOME",
        "label": "Home",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "isDefault": True,
    },
    "restaurant": {
        "name": "Bhukkad Test Kitchen",
        "description": "API integration test restaurant",
        "address": {
            "addressLine1": "100 Food Street",
            "city": "Bangalore",
            "state": "Karnataka",
            "pincode": "560001",
            "latitude": 12.9716,
            "longitude": 77.5946,
        },
        "openingTime": "09:00:00",
        "closingTime": "23:00:00",
        "averageDeliveryTime": 30,
        "minimumOrderAmount": 100.0,
        "deliveryFee": 40.0,
        "freeDeliveryAvailable": True,
        "freeDeliveryAbove": 500.0,
        "isPureVeg": False,
        "fssaiNumber": "12345678901234",
    },
    "category": {
        "name": "Starters",
        "description": "Appetizers",
        "displayOrder": 1,
        "active": True,
    },
    "menu_item": {
        "name": "Paneer Tikka",
        "description": "Grilled cottage cheese",
        "categoryId": "{category_id}",
        "price": 249.0,
        "originalPrice": 299.0,
        "foodType": "VEG",
        "isVeg": True,
        "isSpicy": True,
        "spiceLevel": "MEDIUM",
        "preparationTime": 15,
    },
    "cart_add": {
        "menuItemId": "{menu_item_id}",
        "quantity": 2,
        "specialInstructions": "Extra spicy",
    },
    "order": {
        "restaurantId": "{restaurant_id}",
        "deliveryAddressId": "{address_id}",
        "specialInstructions": "Ring the bell",
        "contactlessDelivery": False,
        "paymentMethod": "CASH_ON_DELIVERY",
    },
    "coupon": {
        "code": "SAVE{timestamp_suffix}",
        "description": "API test coupon",
        "discountType": "PERCENTAGE",
        "discountValue": 10.0,
        "minimumOrderAmount": 100.0,
        "maximumDiscountAmount": 50.0,
        "restaurantId": "{restaurant_id}",
        "usageLimit": 100,
        "perUserLimit": 1,
        "validFrom": "2020-01-01T00:00:00",
        "validUntil": "2030-12-31T23:59:59",
    },
    "review": {
        "orderId": "{order_id}",
        "rating": 5,
        "comment": "Excellent food!",
        "foodRating": 5,
        "deliveryRating": 4,
    },
}
