apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhukkad-app
  namespace: bhukkad
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bhukkad-app
          env:
            - name: JAVA_OPTS
              value: >-
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=50.0
                -XX:+UseG1GC
                -Djava.security.egd=file:/dev/./urandom
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /api/v1/health/ping
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
