apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bhukkad-pgbouncer-pdb
  namespace: bhukkad
  labels:
    app: bhukkad
    component: pgbouncer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bhukkad
      component: pgbouncer
