-- Delivery lifecycle support: the merchant app assigns a rider per order and
-- the rider app transitions picked-up / delivered against that assignment.
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS delivery_agent_id bigint;

CREATE INDEX IF NOT EXISTS idx_orders_delivery_agent
    ON public.orders (delivery_agent_id);

-- Social-order tables (group orders + subscription meal plans) predate the
-- Hibernate mapping and carry plain NOT NULL ids without identity generation;
-- JPA inserts (GenerationType.IDENTITY) therefore fail with a null id.
ALTER TABLE public.group_orders
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.subscription_plans
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

