-- Delivery lifecycle support: the merchant app assigns a rider per order and
-- the rider app transitions picked-up / delivered against that assignment.
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS delivery_agent_id bigint;

CREATE INDEX IF NOT EXISTS idx_orders_delivery_agent
    ON public.orders (delivery_agent_id);

-- Social-order tables (group orders + subscription meal plans + gift cards)
-- may predate the Hibernate mapping and carry plain NOT NULL ids without
-- identity generation; JPA inserts (GenerationType.IDENTITY) then fail. On a
-- fresh V1-baseline database these columns may ALREADY be identity columns,
-- so every ALTER is guarded on information_schema (idempotent, version-safe).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'group_orders' AND column_name = 'id'
                 AND is_identity <> 'YES') THEN
        ALTER TABLE public.group_orders
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'subscription_plans' AND column_name = 'id'
                 AND is_identity <> 'YES') THEN
        ALTER TABLE public.subscription_plans
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- GENERATED ALWAYS blocks Hibernate's IDENTITY strategy (which omits the id
-- and relies on the sequence); BY DEFAULT keeps explicit-id seed inserts legal.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'gift_cards' AND column_name = 'id'
                 AND is_identity = 'ALWAYS') THEN
        ALTER TABLE public.gift_cards
            ALTER COLUMN id SET GENERATED BY DEFAULT;
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'gift_cards' AND column_name = 'id'
                 AND is_identity <> 'YES') THEN
        ALTER TABLE public.gift_cards
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
